---
version: 0.0.1
slug: dnsdist
name: DNSdist
description: dnsdist is a highly DNS-, DoS- and abuse-aware loadbalancer.
url: https://github.com/SharkyRawr/hass-dnsdist
advanced: true
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
#image: gchr.io
init: false
options:
  defaults:
    - 8.8.8.8
    - 8.8.4.4
  customize:
    active: false
    folder: dnsdist
  webserver:
    active: false
    password: "changeme"
    apikey: "changeme"
ports:
  53/tcp: 53
  53/udp: 53
  8083/tcp: 8083
schema:
  defaults:
    - str
  customize:
    active: bool
    folder: str
  webserver:
    active: bool
    password: str
    apikey: str
startup: system